"""Initial migration

Revision ID: 094784f1ceb7
Revises: 
Create Date: 2024-05-20 15:51:19.228865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094784f1ceb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_color', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('favorite_color')

    # ### end Alembic commands ###
